# Chapter 7

In [1]:
# Load pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Read data from BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx
df = pd.read_excel('BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx')
df.head(20)

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyonc√©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22.0,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2.0,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45.0,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48.0,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57.0,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42.0,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
5,2016-10-24 05:16:43.126,No,Male,41.0,USA,Georgia,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
6,2016-10-24 05:16:50.572,Yes,Male,47.0,usa,il,DESPAIR,DESPAIR,JOY,DESPAIR,...,2.0,3 or higher,3 or higher,2.0,2.0,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
7,2016-10-24 05:16:55.324,No,Male,28.0,Canada,Ontario,MEH,JOY,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
8,2016-10-24 05:17:49.292,Yes,Male,44.0,USA,PA,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,2.0,3 or higher,2.0,2.0,Friday,East to West,ESPN,NaN
9,2016-10-24 05:18:51.021,No,Female,41.0,UK,NaN,DESPAIR,DESPAIR,JOY,DESPAIR,...,2.0,1.0,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Sunday,"north to south, but tilted 90 degrees with ste...",ESPN,NaN
10,2016-10-24 05:20:21.125,No,Other,34.0,United States of America,IN,JOY,DESPAIR,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,fnord,Science: Latest News and Headlines,NaN
11,2016-10-24 05:21:19.858,No,Female,46.0,USA,the Mitten,MEH,DESPAIR,MEH,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,I always slice them because the core annoys me,Science: Latest News and Headlines,NaN
12,2016-10-24 05:21:27.708,No,Male,41.0,uSA,California,MEH,DESPAIR,JOY,NaN,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,YAHOO! Finance.,NaN
13,2016-10-24 05:22:12.699,Yes,Male,45.0,Japan,Tokyo,MEH,DESPAIR,MEH,DESPAIR,...,2.0,2.0,3 or higher,3 or higher,2.0,2.0,Sunday,East to West,Science: Latest News and Headlines,NaN
14,2016-10-24 05:22:30.678,No,Male,40.0,united states,ca,MEH,DESPAIR,MEH,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
15,2016-10-24 05:24:08.316,No,Female,31.0,USA,Ny,MEH,DESPAIR,JOY,MEH,...,3 or higher,2.0,1.0,3 or higher,2.0,3 or higher,Friday,Around the world baby,Daily Dish,NaN
16,2016-10-24 05:24:11.446,No,Female,33.0,USA,WA,JOY,DESPAIR,MEH,NaN,...,3 or higher,3 or higher,3 or higher,2.0,1.0,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
17,2016-10-24 05:26:18.333,No,Male,35.0,canada,Ontario,NaN,DESPAIR,JOY,NaN,...,3 or higher,3 or higher,3 or higher,2.0,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
18,2016-10-24 05:26:35.167,Yes,Male,49.0,USA,NJ,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,I cut them and eat with cheese or peanut butter,ESPN,NaN
19,2016-10-24 05:27:00.491,No,Male,44.0,united states,nh,MEH,DESPAIR,MEH,JOY,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,East to West,Science: Latest News and Headlines,NaN

In [3]:
df.dtypes

Timestamp                                                                                                                                    datetime64[ns]
Are you going actually going trick or treating yourself?                                                                                             object
Your gender:                                                                                                                                         object
How old are you?                                                                                                                                     object
Which country do you live in?                                                                                                                        object
                                                                                                                                                  ...
Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]                                    object
Which day do you prefer, Friday or Sunday?                                                                                                           object
Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?            object
When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).                              object
 [York Peppermint Patties] Ignore                                                                                                                   float64
Length: 123, dtype: object

In [4]:
df.shape

(1259, 123)

In [5]:
# Remove duplicates

In [6]:
# Drop duplicates if any
df1=df.drop_duplicates()
df1.shape

(1259, 123)

In [7]:
#Filter out missing data

In [8]:
## columns whcih has NAN or NULL
df.columns[df.isnull().any()]

Index(['Your gender:', 'How old are you?', 'Which country do you live in?',
       'Which state, province, county do you live in?', ' [100 Grand Bar]',
       ' [Anonymous brown globs that come in black and orange wrappers]',
       ' [Any full-sized candy bar]', ' [Black Jacks]',
       ' [Bonkers (the candy)]', ' [Bonkers (the board game)]',
       ...
       'Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling]',
       'Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Beyonc√©]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Bieber]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]',
       'Which day do you prefer, Friday or Sunday?',
       'Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?',
       'When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).',
       ' [York Peppermint Patties] Ignore'],
      dtype='object', length=121)

In [9]:
## Number of missing data per column
df.isnull().sum()

Timestamp                                                                                                                                       0
Are you going actually going trick or treating yourself?                                                                                        0
Your gender:                                                                                                                                    9
How old are you?                                                                                                                               33
Which country do you live in?                                                                                                                  21
                                                                                                                                             ...
Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]                              85
Which day do you prefer, Friday or Sunday?                                                                                                     24
Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?      45
When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).                        37
 [York Peppermint Patties] Ignore                                                                                                            1259
Length: 123, dtype: int64

In [10]:
#Drop columns with Missing values
df1 = df.dropna(axis=1)
print(df1)
# only 2 cloumns left out of 123 columns, with out missing any data

                   Timestamp  \
0    2016-10-24 05:09:23.033
1    2016-10-24 05:09:54.798
2    2016-10-24 05:13:06.734
3    2016-10-24 05:14:17.192
4    2016-10-24 05:14:24.625
...                      ...
1254 2016-10-29 16:53:52.516
1255 2016-10-30 06:53:54.735
1256 2016-10-30 11:06:10.827
1257 2016-10-30 16:07:26.539
1258 2016-10-30 17:06:45.660

     Are you going actually going trick or treating yourself?
0                                                    No
1                                                    No
2                                                    No
3                                                    No
4                                                   Yes
...                                                 ...
1254                                                 No
1255                                                 No
1256                                                 No
1257                                                 No
1258                                                Yes

[1259 rows x 2 columns]

In [11]:
# Drop rows with missing values with threshold 50
df2 = df.dropna(axis=0,how ='all',thresh=50)
print(df2)
df2.shape

                   Timestamp  \
0    2016-10-24 05:09:23.033
1    2016-10-24 05:09:54.798
2    2016-10-24 05:13:06.734
3    2016-10-24 05:14:17.192
4    2016-10-24 05:14:24.625
...                      ...
1254 2016-10-29 16:53:52.516
1255 2016-10-30 06:53:54.735
1256 2016-10-30 11:06:10.827
1257 2016-10-30 16:07:26.539
1258 2016-10-30 17:06:45.660

     Are you going actually going trick or treating yourself? Your gender:  \
0                                                    No               Male
1                                                    No               Male
2                                                    No             Female
3                                                    No               Male
4                                                   Yes               Male
...                                                 ...                ...
1254                                                 No             Female
1255                                                 No               Male
1256                                                 No               Male
1257                                                 No               Male
1258                                                Yes             Female

     How old are you? Which country do you live in?  \
0                22.0                        Canada
1                45.0                           usa
2                48.0                            US
3                57.0                           usa
4                42.0                           USA
...               ...                           ...
1254             52.0                           USA
1255             33.0                 united states
1256              NaN                           NaN
1257             48.0                        canada
1258             44.0                            Us

     Which state, province, county do you live in?  [100 Grand Bar]  \
0                                          Ontario              JOY
1                                               il              MEH
2                                         Colorado              JOY
3                                               il              JOY
4                                     South Dakota              MEH
...                                            ...              ...
1254                                            TX              JOY
1255                                     minnesota              JOY
1256                                           NaN              JOY
1257                                            BC              NaN
1258                                            Nh              JOY

      [Anonymous brown globs that come in black and orange wrappers]  \
0                                               DESPAIR
1                                                   MEH
2                                               DESPAIR
3                                                   MEH
4                                               DESPAIR
...                                                 ...
1254                                            DESPAIR
1255                                            DESPAIR
1256                                                MEH
1257                                            DESPAIR
1258                                                MEH

      [Any full-sized candy bar]  [Black Jacks]  ...  \
0                            JOY            MEH  ...
1                            JOY            JOY  ...
2                            JOY            MEH  ...
3                            JOY            MEH  ...
4                            JOY        DESPAIR  ...
...                          ...            ...  ...
1254                         JOY            MEH  ...
1255                         JOY        DESPAIR  ...
1256                         JOY            NaN  ...
1257                         JOY        DESPAIR  ...
1258                         JOY            JOY  ...

     Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling]  \
0                                           3 or higher
1                                           3 or higher
2                                           3 or higher
3                                           3 or higher
4                                           3 or higher
...                                                 ...
1254                                        3 or higher
1255                               Actually, that's me.
1256                                                NaN
1257                                                1.0
1258                                        3 or higher

     Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams]  \
0                                                   2.0
1                                           3 or higher
2                                           3 or higher
3                                           3 or higher
4                                           3 or higher
...                                                 ...
1254                                        3 or higher
1255                                        3 or higher
1256                                                NaN
1257                                                2.0
1258                                        3 or higher

     Please estimate the degree(s) of separation you have from the following celebrities [Beyonc√©]  \
0                                           3 or higher
1                                           3 or higher
2                                           3 or higher
3                                           3 or higher
4                                           3 or higher
...                                                 ...
1254                                        3 or higher
1255                                        3 or higher
1256                                                NaN
1257                                        3 or higher
1258                                        3 or higher

     Please estimate the degree(s) of separation you have from the following celebrities [Bieber]  \
0                                           3 or higher
1                                           3 or higher
2                                           3 or higher
3                                           3 or higher
4                                           3 or higher
...                                                 ...
1254                                        3 or higher
1255                                        3 or higher
1256                                                NaN
1257                                        3 or higher
1258                                        3 or higher

     Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon]  \
0                                           3 or higher
1                                           3 or higher
2                                           3 or higher
3                                           3 or higher
4                                           3 or higher
...                                                 ...
1254                                                2.0
1255                                        3 or higher
1256                                                NaN
1257                                                2.0
1258                                        3 or higher

     Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]  \
0                                           3 or higher
1                                           3 or higher
2                                           3 or higher
3                                           3 or higher
4                                           3 or higher
...                                                 ...
1254                                        3 or higher
1255                               Actually, that's me.
1256                                                NaN
1257                                        3 or higher
1258                                        3 or higher

     Which day do you prefer, Friday or Sunday?  \
0                                        Friday
1                                        Friday
2                                        Sunday
3                                        Sunday
4                                        Friday
...                                         ...
1254                                     Friday
1255                                     Friday
1256                                     Sunday
1257                                     Sunday
1258                                     Sunday

     Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?  \
0                                        South to North
1                                          East to West
2                                          East to West
3                                        South to North
4                                          East to West
...                                                 ...
1254                                       East to West
1255                    Sinusoidally around the equator
1256                       nne to east to nnw to s to n
1257                                       East to West
1258                                       East to West

     When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).  \
0                    Science: Latest News and Headlines
1                    Science: Latest News and Headlines
2                    Science: Latest News and Headlines
3                    Science: Latest News and Headlines
4                                                  ESPN
...                                                 ...
1254                 Science: Latest News and Headlines
1255                 Science: Latest News and Headlines
1256                 Science: Latest News and Headlines
1257                 Science: Latest News and Headlines
1258                                         Daily Dish

      [York Peppermint Patties] Ignore
0                                  NaN
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
...                                ...
1254                               NaN
1255                               NaN
1256                               NaN
1257                               NaN
1258                               NaN

[1241 rows x 123 columns]

(1241, 123)

# Chapter 8

In [12]:
# Creating  pivot table
pivot = pd.pivot_table(
    data=df2,
    index='Your gender:',
    aggfunc='count',
    values={' [100 Grand Bar]',' [Black Jacks]'}
    
)

In [13]:
print(pivot)

                     [100 Grand Bar]   [Black Jacks]
Your gender:
Female                           381             334
I'd rather not say                25              22
Male                             745             676
Other                             16              14

In [14]:
# Creating  pivot table
pivot2 = pd.pivot_table(
    data=df2,
    index='Your gender:',
    aggfunc='count',
    values={' [Any full-sized candy bar]',' [Anonymous brown globs that come in black and orange wrappers]',' [Bonkers (the candy)]'}
    
)

In [15]:
print(pivot2)

                     [Anonymous brown globs that come in black and orange wrappers]  \
Your gender:
Female                                                            404
I'd rather not say                                                 25
Male                                                              773
Other                                                              17

                     [Any full-sized candy bar]   [Bonkers (the candy)]
Your gender:
Female                                      405                     323
I'd rather not say                           26                      21
Male                                        778                     670
Other                                        16                      13

In [16]:
# Merge Datasets
pd.merge(pivot,pivot2, left_index=True, right_on='Your gender:')

,[100 Grand Bar],[Black Jacks],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Bonkers (the candy)]
Your gender:,,,,,
Female,381,334,404,405,323
I'd rather not say,25,22,25,26,21
Male,745,676,773,778,670
Other,16,14,17,16,13

# Chapter 10

In [17]:
##Grouping with Dicts/Series
my_series = my_series = df2.squeeze()

In [18]:
my_series.groupby('Your gender:',axis=1)

In [19]:
my_series.count()

Timestamp                                                                                                                                    1241
Are you going actually going trick or treating yourself?                                                                                     1241
Your gender:                                                                                                                                 1233
How old are you?                                                                                                                             1211
Which country do you live in?                                                                                                                1222
                                                                                                                                             ...
Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]                            1161
Which day do you prefer, Friday or Sunday?                                                                                                   1219
Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?    1199
When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).                      1206
 [York Peppermint Patties] Ignore                                                                                                               0
Length: 123, dtype: int64

In [20]:
## Split/Apply/Combine
df2['Timestamp'] = df['Timestamp'].dt.date

C:\Users\nbaga\AppData\Local\Temp/ipykernel_44868/1258916191.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Timestamp'] = df['Timestamp'].dt.date

In [21]:
import datetime
df_2016_01_06 = df2.loc[(df2['Timestamp'] >= pd.to_datetime('2016-10-24')) & (df2['Timestamp'] < pd.to_datetime('2016-10-26') )]
df_2016_07_12 = df2.loc[(df2['Timestamp'] >= pd.to_datetime('2016-10-26')) & (df2['Timestamp'] < pd.to_datetime('2016-10-31') )]

C:\Users\nbaga\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:73: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  result = libops.scalar_compare(x.ravel(), y, op)

In [22]:
group_1=df_2016_01_06.groupby(['Timestamp','Your gender:'])

In [23]:
group_1.size()

Timestamp   Your gender:
2016-10-24  Female                228
            I'd rather not say     14
            Male                  514
            Other                   9
2016-10-25  Female                 85
            I'd rather not say      4
            Male                   57
            Other                   1
dtype: int64

In [24]:
group_2=df_2016_07_12.groupby(['Timestamp','Your gender:'])

In [25]:
group_2.size()

Timestamp   Your gender:
2016-10-26  Female                 13
            Male                   19
            Other                   2
2016-10-27  Female                 61
            I'd rather not say      8
            Male                  176
            Other                   4
2016-10-28  Female                 15
            Male                   11
            Other                   1
2016-10-29  Female                  4
            Male                    3
2016-10-30  Female                  1
            Male                    3
dtype: int64

In [26]:
group_1[' [100 Grand Bar]'].count()

Timestamp   Your gender:
2016-10-24  Female                216
            I'd rather not say     14
            Male                  490
            Other                   8
2016-10-25  Female                 74
            I'd rather not say      3
            Male                   47
            Other                   1
Name:  [100 Grand Bar], dtype: int64

# Chapter 11

In [27]:
#Convert string to date time

##1 converting existing Timestamp to str
df2['str_timestamp']=df2['Timestamp'].astype(str)

C:\Users\nbaga\AppData\Local\Temp/ipykernel_44868/49790966.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['str_timestamp']=df2['Timestamp'].astype(str)

In [28]:
## Convert back to Datetime
df2['str_to_timestamp']=pd.to_datetime(df2['str_timestamp'], format='%Y-%m-%d')

C:\Users\nbaga\AppData\Local\Temp/ipykernel_44868/3771956949.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['str_to_timestamp']=pd.to_datetime(df2['str_timestamp'], format='%Y-%m-%d')

In [29]:
#Generate date range

rng = pd.date_range(start='2016-10-1', end='2016-10-31', periods=1241)
df2.insert(2,'Rangedate',rng)
df2

,Timestamp,Are you going actually going trick or treating yourself?,Rangedate,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],...,Please estimate the degree(s) of separation you have from the following celebrities [Beyonc√©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore,str_timestamp,str_to_timestamp
0,2016-10-24,No,2016-10-01 00:00:00.000000000,Male,22.0,Canada,Ontario,JOY,DESPAIR,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN,2016-10-24,2016-10-24
1,2016-10-24,No,2016-10-01 00:34:50.322580645,Male,45.0,usa,il,MEH,MEH,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10-24,2016-10-24
2,2016-10-24,No,2016-10-01 01:09:40.645161290,Female,48.0,US,Colorado,JOY,DESPAIR,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10-24,2016-10-24
3,2016-10-24,No,2016-10-01 01:44:30.967741935,Male,57.0,usa,il,JOY,MEH,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN,2016-10-24,2016-10-24
4,2016-10-24,Yes,2016-10-01 02:19:21.290322580,Male,42.0,USA,South Dakota,MEH,DESPAIR,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN,2016-10-24,2016-10-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29,No,2016-10-30 21:40:38.709677419,Female,52.0,USA,TX,JOY,DESPAIR,JOY,...,3 or higher,3 or higher,2.0,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10-29,2016-10-29
1255,2016-10-30,No,2016-10-30 22:15:29.032258064,Male,33.0,united states,minnesota,JOY,DESPAIR,JOY,...,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN,2016-10-30,2016-10-30
1256,2016-10-30,No,2016-10-30 22:50:19.354838710,Male,NaN,NaN,NaN,JOY,MEH,JOY,...,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN,2016-10-30,2016-10-30
1257,2016-10-30,No,2016-10-30 23:25:09.677419355,Male,48.0,canada,BC,NaN,DESPAIR,JOY,...,3 or higher,3 or higher,2.0,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10-30,2016-10-30
1258,2016-10-30,Yes,2016-10-31 00:00:00.000000000,Female,44.0,Us,Nh,JOY,MEH,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN,2016-10-30,2016-10-30